config/routes.rb
Rails.application.routes.draw do
  root 'recipes#index'
  resources :recipes do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :recipe

  validates :name, :rating, :comment, presence: :true
  validates_length_of :comment, maximum:300
  validates_inclusion_of :rating , in: [0,1,2,3,4,5]
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :comments , dependent: :destroy
  validates :name, :stuff, :duration, :prepare_mode, presence:true
  validates_length_of :stuff, maximum: 300
  validates_length_of :prepare_mode, maximum: 600
  validates_numericality_of :calories, greater_than_or_equal_to: 0, presence:true
  validates_format_of :poster, allow_blank: true, with: /\w+\.(gif|jpg|png|jpeg)\z/i, message: "use only gif, jpg, jpeg or png files."

  KIND = %w(Desserts Drinks Snacks Pasta)
  validates_inclusion_of :kind, in: KIND

  def light?
    calories < 100
  end

  def self.created_at
    where('created_at <= ?', Time.now).order('created_at desc')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @recipe = Recipe.find(params[:recipe_id])
    @comments = @recipe.comments
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.created_at
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def edit 
    @recipe = Recipe.find(params[:id])
  end

  def update 
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      redirect_to @recipe, notice: "successfully updated recipe!"
    else
      render :edit
    end
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to @recipe, notice: "successfully created recipe!"
    else
      render :new
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_url, alert: "Successfully deleted recipe"
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :stuff, :calories, :prepare_mode, :cost, :kind, :portion, :duration, :poster, :intro)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_messages
    messages = ""
    [:notice, :alert].each { |type| 
      if flash[type]
        messages += "<div class='alert alert--#{type}'><ion-icon name='close'></ion-icon><p>#{flash[type]}</p></div>"
      end
    }
    messages.html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def calories_formater(recipe)
    if recipe.light?
      content_tag(:strong, "Light (#{recipe.calories} Calories)")
    else 
      content_tag(:strong, "#{recipe.calories} Calories")
    end
  end

  def image(recipe)
    if recipe.poster.blank?
      image_tag('https://jis.gov.jm/media/blank.png')
    else
      image_tag(recipe.poster)
    end
  end
end

app/views/comments/index.html.erb
<h1>Eu vou ser apagado assim que possivel</h1>
<% if @recipe.comments.present? %>
  <div>
    <ul>
      <% @comments.each do |comment| %>
      <li>
        <p><%= comment.name %></p>
        <span><%= pluralize(comment.rating, 'Star', 'Stars')%></span>
        <small><%= time_ago_in_words(comment.created_at) %> ago</small>
        <p><%= comment.comment %></p>
      </li>
      <% end %>
    </ul>
    <%= link_to "Back to Recipes", @recipe%>
  </div>
<% else %>
  <div>There is no comments yet</div>
<% end %>

app/views/layouts/_errors.html.erb
 <% if @recipe.errors.any? %>
  <div>
      <ul>
        <% @recipe.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="footer__resume">
      <h3 class="title title__subtitle title__subtitle--footer">The History Behind</h3>
      <p>This website is made with the purpose of deepen the knowledge of the framework Ruby on Rails and also a challenge to make it with the best design and user experience possibles. Hope you had enjoyed!</p>
  </div>

  <div>
    <h3 class="title title__subtitle title__subtitle--footer">About the Project</h3>
    <div class="footer__about">
      <p>This project was made using:</p>
      <ul>
        <li>Ruby on Rails <i class="fas fa-angle-left"></i></li>
        <li>Sass <i class="fas fa-angle-left"></i></li>
        <li>Bem <i class="fas fa-angle-left"></i></li>
      </ul>
    </div>
  </div>

  <div>
    <h3 class="title title__subtitle title__subtitle--footer">Where you can find me?</h3>
    <div class="footer__links">
      <a href="https://github.com/rochabianca" target="_blank"><i class="fab fa-github"></i></a>
      <a href="https://www.behance.net/Rochabianca" target="_blank"><i class="fab fa-behance"></i></a>
      <a href="https://www.linkedin.com/in/bianca-rocha-0a6794100/" target="_blank"><i class="fab fa-linkedin-in"></i></a>
      <a href="mailto:bianca.rocha1711@gmail.com" target="_blank"><i class="fas fa-envelope"></i></a>
    </div>
  </div>
</footer>
 <div class="footer__end">
    <p>Made with <i class="fas fa-heart"></i> by <a href="https://github.com/rochabianca" target="_blank">Bianca Rocha</a></p>
</div>

app/views/layouts/_header.html.erb
<header class="header">
  <div class="header__logo">
    <%= link_to(root_path) do %>
      <%= image_tag 'logo.png', alt: 'Logo', class: "header__logo--image" %>
      <span class="header__logo--name">Grandma's recipes</span>
    <% end %>
  </div>
  
  <div class="header__item">
    <%= link_to "New Recipe", new_recipe_path %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ISawOnTheInternet</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Alegreya+SC:400,700|Alegreya:400,700" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header'%>
    <%= flash_messages %>
    <%= yield %>
    <%= render 'layouts/footer'%>
    <script src="https://unpkg.com/ionicons@4.1.2/dist/ionicons.js"></script>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <%= render 'layouts/errors' %>
 
  <div>
    <%= f.label :Name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :Type %>
    <%= f.select :kind, Recipe::KIND, prompt: "Choose your option"  %>
  </div>

  <div>
    <%= f.label :Portions %>
    <%= f.text_field :portion %>
  </div>

   <div>
    <%= f.label :Time_To_Prepare %>
    <%= f.time_select :duration %>
  </div>

  <div>
    <%= f.label :Intro %>
    <%= f.text_area :intro, cols: 20, rows: 7 %>
  </div>

  <div>
    <%= f.label :Ingridients %>
    <%= f.text_area :stuff, cols: 20, rows: 7 %>
  </div>

  <div>
    <%= f.label :Calories %>
    <%= f.number_field :calories %>
  </div>

  <div>
    <%= f.label :Prepare_Mode %>
    <%= f.text_area :prepare_mode, cols: 20, rows: 7 %>
  </div>

  <div>
    <%= f.label :Cost %>
    <%= f.number_field :cost %>
  </div>

  <div>
    <%= f.label :Poster %>
    <%= f.text_field :poster, placeholder: ".GIF, .JPEG ou .PNG" %>
  </div>

  <div>
    <%= f.submit %>
    <%= link_to "Cancel", root_path %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>
<%= render 'form' %>

app/views/recipes/index.html.erb
<div class="owl-carousel owl-theme">
  <div class="item"> <%= image_tag('desserts.png') %> </div>
  <div class="item"> <%= image_tag('drinks.png') %> </div>
  <div class="item"> <%= image_tag('snaks.png') %> </div>
</div>

<h1 class="title">Week's Menu</h1>

<section class="grid">
  <div class="grid__column grid__column--3">
    <h2 class="title title__subtitle">Pasta</h2>
    <ul class="recipe-list">
    <% pasta = @recipes.where(kind: 'Pasta') %>
      <% pasta.each_with_index do |recipe| %>
        <li>
          <%= link_to(recipe) do %>
            <h3 class="recipe-list__name"><%= recipe.name %></h3>
            <p class="recipe-list__resume"><%= recipe.intro %></p>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="grid__column grid__column--3">
    <h2 class="title title__subtitle">Drinks</h2>
    <ul class="recipe-list">
      <% @recipes.where(kind: 'Drinks').each do |recipe| %>
        <li>
          <%= link_to(recipe) do %>
            <h3 class="recipe-list__name"><%= recipe.name %></h3>
            <p class="recipe-list__resume"><%= recipe.intro %></p>
          <% end %>
        <li>
      <% end %>
    </ul>
  </div>

  <div class="grid__column grid__column--3">
    <h2 class="title title__subtitle">Snacks</h2>
    <ul class="recipe-list">
      <% @recipes.where(kind: 'Snacks').each do |recipe| %>
        <li>
          <%= link_to(recipe) do %>
            <h3 class="recipe-list__name"><%= recipe.name %></h3>
            <p class="recipe-list__resume"><%= recipe.intro %></p>
          <% end %>
        <li>
      <% end %>
    </ul>
  </div>

  <div class="grid__column grid__column--3">
    <h2 class="title title__subtitle">Desserts</h2>
    <ul class="recipe-list">
      <% @recipes.where(kind: 'Desserts').each do |recipe| %>
        <li>
          <%= link_to(recipe) do %>
            <h3 class="recipe-list__name"><%= recipe.name %></h3>
            <p class="recipe-list__resume"><%= recipe.intro %></p>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</section>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>
<%= render 'form' %>

app/views/recipes/show.html.erb
<header>
  <h1><%= @recipe.name %></h1>
  <%= image(@recipe) %>
</header>

<div>
  <%= @recipe.kind %>
  <%= @recipe.duration.to_formatted_s(:time) %> min
  <%= pluralize(@recipe.portion, 'portion', 'portions') %>
</div>

<h2>Ingridients</h2>
<p>
  <%= @recipe.stuff %>
</p>

<h2>Calories</h2>
<p> <%= @recipe.calories %></p>

<h2>Prepare Mode</h2>
<p>
  <%= @recipe.prepare_mode %>
</p>

<h3>Cost</h3>
<p><%= number_to_currency(@recipe.cost) %></p>

<%= link_to "Back to Recipes", recipes_path %>
<%= link_to "Edit Recipe", edit_recipe_path(@recipe) %>
<%= link_to "Delete Recipe", recipe_path(@recipe), method: :delete, data:{confirm: "Are you sure?"} %>
<%= link_to pluralize(@recipe.comments.length, 'Comment', 'Comments'), recipe_comments_path(@recipe) %>